# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: pretrain
  - model: deepfont_ae
  - callbacks: pretrain
  - logger: null # set logger here or use command line (e.g. `python pretrain.py logger=tensorboard`)
  - trainer: pretrain
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

# task name, determines output directory path
task_name: "pretrain"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python pretrain.py tags="[first_tag, second_tag]"`
tags: ["default_pretrain"]

# set False to skip model training
train: True

# simply provide checkpoint path to resume training
ckpt_path: null
